# Allow compute credits usage for collaborators and anything pushed to the
# master, staging, and trying branches. (So bors can use them.)
use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' || $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH == 'staging' || $CIRRUS_BRANCH == 'trying'

success_task:
  name: CI success
  container: {image: "busybox"}
  depends_on:
    - pylint
    - clang_lint
    - test

pylint_task:
  container:
    image: python:3.11-slim
  install_script:
    - pip install pylint pytest
  script:
    - pylint --version
    - pylint test

clang_lint_task:
  container:
    image: debian:12-slim
  install_script:
    - "apt-get update && apt-get install -y clang clang-tools make"
  script:
    - make lint

test_task:
  container:
    image: python:3.11-slim
  env:
    matrix:
      - SANITIZE:
      - SANITIZE: address,undefined
      - SANITIZE: memory
  install_script:
    - "apt-get update && apt-get install -y clang make"
    - pip install pytest
  script:
    - make test
